{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-13692",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://github.com/pgjdbc/pgjdbc/commit/14b62aca4764d496813f55a43d050b017e01eb65",
                    "name": "https://github.com/pgjdbc/pgjdbc/commit/14b62aca4764d496813f55a43d050b017e01eb65",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.13",
                    "name": "https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.13",
                    "refsource": "CONFIRM",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "PostgreSQL JDBC Driver (aka PgJDBC) before 42.2.13 allows XXE."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-06-04T16:15Z",
    "lastModifiedDate": "2020-06-04T16:33Z"
}