{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-13294",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13294.json",
                    "name": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13294.json",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/222829",
                    "name": "https://gitlab.com/gitlab-org/gitlab/-/issues/222829",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://hackerone.com/reports/892427",
                    "name": "https://hackerone.com/reports/892427",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "In GitLab before 13.0.12, 13.1.6 and 13.2.3, access grants were not revoked when a user revoked access to an application."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-08-10T14:15Z",
    "lastModifiedDate": "2020-08-10T14:19Z"
}