{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-13317",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13317.json",
                    "name": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13317.json",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/215703",
                    "name": "https://gitlab.com/gitlab-org/gitlab/-/issues/215703",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://hackerone.com/reports/858671",
                    "name": "https://hackerone.com/reports/858671",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "A vulnerability was discovered in GitLab versions before 13.1.10, 13.2.8, and 13.3.4. An insufficient check in the GraphQL api allowed a maintainer to delete a repository."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-09-14T20:15Z",
    "lastModifiedDate": "2020-09-14T20:17Z"
}