{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-10725",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://bugs.dpdk.org/show_bug.cgi?id=270",
                    "name": "https://bugs.dpdk.org/show_bug.cgi?id=270",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-10725",
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-10725",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https://www.openwall.com/lists/oss-security/2020/05/18/2",
                    "name": "https://www.openwall.com/lists/oss-security/2020/05/18/2",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "A flaw was found in DPDK version 19.11 and above that allows a malicious guest to cause a segmentation fault of the vhost-user backend application running on the host, which could result in a loss of connectivity for the other guests running on that host. This is caused by a missing validity check of the descriptor address in the function `virtio_dev_rx_batch_packed()`."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-05-20T14:15Z",
    "lastModifiedDate": "2020-05-20T14:37Z"
}