{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2018-1501",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/141226",
                    "name": "ibm-guardium-cve20181501-info-disc (141226)",
                    "refsource": "XF",
                    "tags": []
                },
                {
                    "url": "https://www.ibm.com/support/pages/node/6321357",
                    "name": "https://www.ibm.com/support/pages/node/6321357",
                    "refsource": "CONFIRM",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "IBM Security Guardium 10.5, 10.6, and 11.0 could allow an unauthorized user to obtain sensitive information due to missing security controls. IBM X-Force ID: 141226."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-08-26T19:15Z",
    "lastModifiedDate": "2020-08-26T20:32Z"
}