{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-11810",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://bugzilla.suse.com/show_bug.cgi?id=1169925",
                    "name": "https://bugzilla.suse.com/show_bug.cgi?id=1169925",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https://community.openvpn.net/openvpn/ticket/1272",
                    "name": "https://community.openvpn.net/openvpn/ticket/1272",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https://github.com/OpenVPN/openvpn/commit/37bc691e7d26ea4eb61a8a434ebd7a9ae76225ab",
                    "name": "https://github.com/OpenVPN/openvpn/commit/37bc691e7d26ea4eb61a8a434ebd7a9ae76225ab",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FGHHV4YZANZW45KZTJJGVGPFMSXYRCKZ/",
                    "name": "FEDORA-2020-c1cb4ebcd9",
                    "refsource": "FEDORA",
                    "tags": []
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JII7RYYYRBPQNEGGVSOXCM7JUZ43T3VH/",
                    "name": "FEDORA-2020-969414e05b",
                    "refsource": "FEDORA",
                    "tags": []
                },
                {
                    "url": "https://patchwork.openvpn.net/patch/1079/",
                    "name": "https://patchwork.openvpn.net/patch/1079/",
                    "refsource": "CONFIRM",
                    "tags": []
                },
                {
                    "url": "https://security-tracker.debian.org/tracker/CVE-2020-11810",
                    "name": "https://security-tracker.debian.org/tracker/CVE-2020-11810",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "An issue was discovered in OpenVPN 2.4.x before 2.4.9. An attacker can inject a data channel v2 (P_DATA_V2) packet using a victim's peer-id. Normally such packets are dropped, but if this packet arrives before the data channel crypto parameters have been initialized, the victim's connection will be dropped. This requires careful timing due to the small time window (usually within a few seconds) between the victim client connection starting and the server PUSH_REPLY response back to the client. This attack will only work if Negotiable Cipher Parameters (NCP) is in use."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-04-27T15:15Z",
    "lastModifiedDate": "2020-04-27T15:20Z"
}