{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-11058",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://github.com/FreeRDP/FreeRDP/commit/3627aaf7d289315b614a584afb388f04abfb5bbf",
                    "name": "https://github.com/FreeRDP/FreeRDP/commit/3627aaf7d289315b614a584afb388f04abfb5bbf",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://github.com/FreeRDP/FreeRDP/issues/6011",
                    "name": "https://github.com/FreeRDP/FreeRDP/issues/6011",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://github.com/FreeRDP/FreeRDP/security/advisories/GHSA-wjg2-2f82-466g",
                    "name": "https://github.com/FreeRDP/FreeRDP/security/advisories/GHSA-wjg2-2f82-466g",
                    "refsource": "CONFIRM",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "In FreeRDP after 1.1 and before 2.0.0, a stream out-of-bounds seek in rdp_read_font_capability_set could lead to a later out-of-bounds read. As a result, a manipulated client or server might force a disconnect due to an invalid data read. This has been fixed in 2.0.0."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-05-12T21:15Z",
    "lastModifiedDate": "2020-05-12T21:33Z"
}